/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    OutlineNode: typeof import('./src/components/OutlineNode.vue')['default']
    OutlineTree: typeof import('./src/components/OutlineTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsBar: typeof import('./src/components/TabsBar.vue')['default']
  }
}
